import { Dungeon, Achievement, Character, Equipment } from './types';

export const INITIAL_GOLD = 1000;
export const INITIAL_TICKETS = 3;

export const JOB_INFO = {
  warrior: {
    label: '戦士',
    desc: '攻撃力が高く、高難度ダンジョンも力で突破する。物理攻撃力+50%',
    color: 'text-rose-600 bg-rose-50 border-rose-200',
    statBonus: '攻撃力+50%',
  },
  thief: {
    label: 'シーフ',
    desc: 'アイテム探索能力が高く、レア素材の獲得率が上昇する。素材獲得率+50%',
    color: 'text-amber-600 bg-amber-50 border-amber-200',
    statBonus: '素材獲得+50%',
  },
  mage: {
    label: '魔術師',
    desc: '時空魔法を操り、ダンジョンへの派遣時間を短縮する。派遣時間-25%',
    color: 'text-indigo-600 bg-indigo-50 border-indigo-200',
    statBonus: '派遣時間-25%',
  },
};

export const INITIAL_DUNGEONS: Dungeon[] = [
  {
    id: 'dungeon_1',
    name: '初心者の洞窟',
    recommendAtk: 200,
    durationSec: 8,
    goldReward: 200,
    ironReward: 5,
    gemReward: 0,
    dragonReward: 0,
    isInfinite: false,
    description: 'スライムやゴブリンが徘徊する安全な洞窟。まずはここから始めよう。',
  },
  {
    id: 'dungeon_2',
    name: '魔狼の森',
    recommendAtk: 1200,
    durationSec: 25,
    goldReward: 800,
    ironReward: 12,
    gemReward: 3,
    dragonReward: 0,
    isInfinite: false,
    description: '俊敏な森林ウルフが群れる。レベルを上げて武器を装備してから挑もう。',
  },
  {
    id: 'dungeon_3',
    name: '竜の巣',
    recommendAtk: 6500,
    durationSec: 60,
    goldReward: 3500,
    ironReward: 30,
    gemReward: 15,
    dragonReward: 2,
    isInfinite: false,
    description: '凶悪なワイバーンやドラゴンのねぐら。高レア武器のクラフト素材が手に入る。',
  },
  {
    id: 'dungeon_4',
    name: '深海の古宮',
    recommendAtk: 18000,
    durationSec: 75,
    goldReward: 6000,
    ironReward: 50,
    gemReward: 20,
    dragonReward: 5,
    isInfinite: false,
    description: '海底に沈む古代の宮殿。水棲魔獣の妨害を避けつつ、太古の至宝を探せ。',
  },
  {
    id: 'dungeon_5',
    name: '精霊の森深部',
    recommendAtk: 35000,
    durationSec: 90,
    goldReward: 12000,
    ironReward: 80,
    gemReward: 35,
    dragonReward: 8,
    isInfinite: false,
    description: '精霊たちの加護と魔力が満ちた神秘の秘境。高純度な魔導石が大量に採取できる。',
  },
  {
    id: 'dungeon_6',
    name: '暗黒デスの迷宮',
    recommendAtk: 65000,
    durationSec: 120,
    goldReward: 25000,
    ironReward: 130,
    gemReward: 60,
    dragonReward: 15,
    isInfinite: false,
    description: '凶暴な死神の影が忍び寄る奈落迷宮。装備強化を極めたメンバーが求められる。',
  },
  {
    id: 'dungeon_7',
    name: '白熱の流星火山',
    recommendAtk: 95000,
    durationSec: 150,
    goldReward: 42000,
    ironReward: 180,
    gemReward: 90,
    dragonReward: 25,
    isInfinite: false,
    description: '宇宙より降り注いだ鉱石がマグマと混ざり合う山。竜の超希少鉱脈が眠る。',
  },
  {
    id: 'dungeon_ex_1',
    name: '【超高難易度】超越光天宮',
    recommendAtk: 180000,
    durationSec: 180,
    goldReward: 65000,
    ironReward: 260,
    gemReward: 150,
    dragonReward: 35,
    isInfinite: false,
    description: '【超高難易度】天上界の理を超越した光の守護セラフィムが門番を務める神域。',
  },
  {
    id: 'dungeon_ex_2',
    name: '【超高難易度】虚無終焉界',
    recommendAtk: 420000,
    durationSec: 200,
    goldReward: 140000,
    ironReward: 450,
    gemReward: 280,
    dragonReward: 65,
    isInfinite: false,
    description: '【超高難易度】存在そのものが否定される無の地。敵の攻撃力は理不尽を極める。',
  },
  {
    id: 'dungeon_ex_3',
    name: '【超高難易度】神魔大戦場跡',
    recommendAtk: 980000,
    durationSec: 240,
    goldReward: 320000,
    ironReward: 900,
    gemReward: 600,
    dragonReward: 150,
    isInfinite: false,
    description: '【超高難易度】かつて神と魔が衝突した破壊の地。今も滅びの剣風が吹き、狂暴な霊体が跋扈する。',
  },
  {
    id: 'dungeon_ex_4',
    name: '【伝説究極】輪廻無尽創生球',
    recommendAtk: 2500000,
    durationSec: 300,
    goldReward: 850000,
    ironReward: 2000,
    gemReward: 1200,
    dragonReward: 400,
    isInfinite: false,
    description: '【伝説究極】宇宙の始まりと終わりを司るコア。神の領域に等しく、無限のクラフト素材が凝縮する。',
  },
  {
    id: 'dungeon_ex_5',
    name: '【絶望の監獄】アポカリプス',
    recommendAtk: 5000000,
    durationSec: 360,
    goldReward: 1800000,
    ironReward: 5000,
    gemReward: 3000,
    dragonReward: 1000,
    isInfinite: false,
    description: '【終焉の試練】完璧な神話防具と超会心ビルドを施した最強戦士のみが突破可能な絶対極限。',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    title: '会社設立記念',
    description: '総獲得ゴールドが 5,000 に到達（全社員の攻撃力 +3%）',
    targetType: 'gold_total',
    targetCount: 5000,
    unlocked: false,
    buffValue: 3,
  },
  {
    id: 'ach_2',
    title: '中堅企業への跳躍',
    description: '総獲得ゴールドが 100,000 に到達（全社員の攻撃力 +5%）',
    targetType: 'gold_total',
    targetCount: 100000,
    unlocked: false,
    buffValue: 5,
  },
  {
    id: 'ach_3',
    title: '世界屈指のメガコープ',
    description: '総獲得ゴールドが 10,000,000 に到達（全社員の攻撃力 +10%）',
    targetType: 'gold_total',
    targetCount: 10000000,
    unlocked: false,
    buffValue: 10,
  },
  {
    id: 'ach_4',
    title: '無限の富の創造者',
    description: '総獲得ゴールドが 1,000,000,000 に到達（全社員の攻撃力 +25%）',
    targetType: 'gold_total',
    targetCount: 1000000000,
    unlocked: false,
    buffValue: 25,
  },
  {
    id: 'ach_5',
    title: '運を味方につける経営者',
    description: 'レジェンダリー装備を 2個所持（全員の攻撃力 +5%）',
    targetType: 'legendary_count',
    targetCount: 2,
    unlocked: false,
    buffValue: 5,
  },
  {
    id: 'ach_6',
    title: '大財閥の目利き',
    description: 'レジェンダリー装備を 10個所持（全員の攻撃力 +15%）',
    targetType: 'legendary_count',
    targetCount: 10,
    unlocked: false,
    buffValue: 15,
  },
  {
    id: 'ach_7',
    title: '少数精鋭',
    description: '全社員の合計レベルが 30 に到達（全員の攻撃力 +5%）',
    targetType: 'level_total',
    targetCount: 30,
    unlocked: false,
    buffValue: 5,
  },
  {
    id: 'ach_8',
    title: '超エリート軍団',
    description: '全社員の合計レベルが 200 に到達（全員の攻撃力 +15%）',
    targetType: 'level_total',
    targetCount: 200,
    unlocked: false,
    buffValue: 15,
  },
  {
    id: 'ach_9',
    title: '敏腕管理者',
    description: 'ダンジョン派遣回数が 50回に到達（全員の攻撃力 +5%）',
    targetType: 'dispatch_count',
    targetCount: 50,
    unlocked: false,
    buffValue: 5,
  },
  {
    id: 'ach_10',
    title: '奈落の探求者',
    description: '「極限の奈落」の到達階層が 5F に到達（全員の攻撃力 +5%）',
    targetType: 'deepest_floor',
    targetCount: 5,
    unlocked: false,
    buffValue: 5,
  },
  {
    id: 'ach_11',
    title: '奈落の覇王',
    description: '「極限の奈落」の到達階層が 30F に到達（全員の攻撃力 +15%）',
    targetType: 'deepest_floor',
    targetCount: 30,
    unlocked: false,
    buffValue: 15,
  },
];

// Employee name components for random generation
export const FIRST_NAMES = [
  'リュウ', 'ハルト', 'ソウタ', 'エルマ', 'リオン', 'セリア', 'アイシャ', 'カイ', 'ルシア', 'ユウマ',
  'レン', 'アリシア', 'カレン', 'ロイ', 'フィーナ', 'ディラン', 'メイ', 'シルヴィ', 'ノア', 'レオン'
];

export const LAST_NAMES = [
  '・アドラー', '・スターク', '・クライン', '・ヴァイス', '・フォレスト', '・ハミルトン', '・ミラー',
  '・ロックハート', '・アッシュ', '・ローゼズ', '・ベネット', '・ベルグ', '・クラウン', '・アイアン'
];

// Equipment prefixes/suffixes based on rarity
export const WEAPON_NAMES = {
  common: ['なまくらの剣', 'ブロンズソード', '木刀', 'ショートダガー', '鉄のナイフ'],
  rare: ['鋼鉄の大剣', '漆黒の短剣', '銀の細剣', 'ウィンドカリバー', '精霊の杖'],
  epic: ['竜殺しの大剣', 'デストロイヤー', 'シャドウ牙王刃', '大魔導シグマの杖', '天ノ尾羽張'],
  legendary: ['光剣エクスカリバー', '獄炎大邪帝ガンダール', '神曲創世ラグナロク', '虚無の魔水晶', '絶対神オーディンランス'],
};

export const ARMOR_NAMES = {
  common: ['ボロい服', 'レザーベスト', '錆びた布鎧', '冒険者の服', 'うすい胸当て'],
  rare: ['鉄のラメラー', '狩人のケープ', '紅蓮の軽鎧', '水晶のローブ', '騎士の甲冑'],
  epic: ['金剛のドワーフプレート', '光の神官聖衣', '氷結のアブソリュート', '忍びの隠密黒装束', '天界の輝甲'],
  legendary: ['竜王の神鋼鎧', '不死鳥の聖鎧', '死神のダークプレート', '神代のオメガバリア', '天帝の煌めく羽衣'],
};

export const SUBSTAT_POOL = [
  { effectType: 'atk_pct', label: '攻撃力%', min: 3, max: 25 },
  { effectType: 'gold_pct', label: 'ゴールド獲得%', min: 5, max: 30 },
  { effectType: 'time_dec', label: '派遣時間短縮%', min: 2, max: 15 },
  { effectType: 'crit_rate', label: '会心率%', min: 2, max: 20 },
] as const;

export const CRAFT_RECIPES = [
  {
    id: 'craft_common',
    name: '一般装備の製造',
    rarity: 'common' as const,
    goldCost: 300,
    ironCost: 24,
    magicCost: 0,
    dragonCost: 0,
    desc: '実用的なコモン〜レア装備を作る。',
  },
  {
    id: 'craft_rare',
    name: '精巧な装備の製造',
    rarity: 'rare' as const,
    goldCost: 1500,
    ironCost: 75,
    magicCost: 5,
    dragonCost: 0,
    desc: 'レア以上確定、稀にエピック装備が誕生する。',
  },
  {
    id: 'craft_epic_advanced',
    name: '【特級】魔導竜牙の精錬',
    rarity: 'epic' as const,
    goldCost: 20000,
    ironCost: 450,
    magicCost: 75,
    dragonCost: 15,
    desc: 'エピック以上の武具を確実に製造。魔導工芸の粋をつくした極上の製法。',
  },
  {
    id: 'craft_epic',
    name: '極限の装備製造',
    rarity: 'epic' as const,
    goldCost: 8000,
    ironCost: 180,
    magicCost: 25,
    dragonCost: 4,
    desc: 'エピック以上確定、レジェンダリーが低確率で出現する。特級金型を使用。',
  },
  {
    id: 'craft_legendary_absolute',
    name: '【神話】古代賢者の秘儀',
    rarity: 'legendary' as const,
    goldCost: 120000,
    ironCost: 3000,
    magicCost: 1000,
    dragonCost: 500,
    desc: '【超極限素材消費】てっこうせき3000・まほう結晶1000・竜のウロコ500個をすべて注ぎ込む。圧倒的なステータス補正と極限レベルの付加オプションを秘めた最高峰「レジェンダリー」装備を100%確定で鍛造します。',
  },
];
